name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache .stack
        id: cache-stack
        uses: actions/cache@v4
        with:
          path: ~/.stack
          key: v2-stack-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            v2-stack-
      - name: Cache .stack/pantry
        id: cache-pantry
        uses: actions/cache@v4
        with:
          path: ~/.stack-temp/pantry
          key: v2-pantry-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            v2-pantry-
      - name: Move .stack/pantry to temp
        uses: matsubara0507/actions/move-files@master
        with:
          source_dir: ~/.stack-temp/pantry
          source_files: |
            pantry
          target_dir: ~/.stack
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        name: Setup Haskell
        with:
          ghc-version: 9.8.4
          cabal-version: 3.12.1.0
          enable-stack: true
          stack-version: 'latest'
      - name: Install sass
        run: |
          wget -O /opt/sass.tar.gz https://github.com/sass/dart-sass/releases/download/1.86.3/dart-sass-1.86.3-linux-x64.tar.gz
          cd /opt
          sudo tar xvf sass.tar.gz
          sudo mv dart-sass/* /usr/local/bin/
          cd -
      - name: Install dependencies
        run: stack --system-ghc build
      - name: Build blog
        run: |
          stack --system-ghc exec -- blog clean
          stack --system-ghc exec -- blog build
      - name: Checkout blog branch
        uses: actions/checkout@v2
        with:
          ref: blog
          path: blog
      - name: Move assets to blog branch
        run: |
          cp -r _site/* blog/
      - name: Set git config
        run: |
          cd blog
          git config --local user.email yoshitsugu@users.noreply.github.com
          git config --local user.name yoshitsugu
          git config pull.rebase false
      - name: Commit and Push
        run: |
          cd blog
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am "Commit by GitHub Actions (triggered by ${GITHUB_SHA})"
          git pull --prune
          git push origin blog
